language: node_js
node_js:
  - "6.1"
  - "6"
  - "5.11"
  - "iojs"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq redis-server
  - npm install --dev
