sudo: required
services:
  - docker
scripts:
  docker-compose -f docker-compose.test.yml -p epitech-search build
  docker-compose -f docker-compose.test.yml -p epitech-search up --abort-on-container-exit
